import { cleanEnv, str, num } from "envalid";

const env = cleanEnv(process.env, {
  BOT_TOKEN: str(),
  TOKEN_CONTRACT: str(),
  BOT_NAME: str(),
  TOKEN_BOT_NOTIFY: str(),
  MASTER_WALLET: str(),
  MASTER_WALLET_PRIVATE_KEY: str(),
  RPC_NODE_1: str(),
  RPC_NODE_2: str(),
  RPC_NODE_3: str(),
  ADMIN_ID: str(),
  GROUP_ID: str(),
  CHANNEL_ID: str(),
  GROUP_URL: str(),
  CHANNEL_URL: str(),
  RATE_REFFERAL: num(),
  MINE_RATE: num(),
  MAX_SEND: num(),
  PROFIT_BONUS_PACKAGE: num(),
  PRICE_TOKEN: num(),
  REDIS_HOST: str(),
  REDIS_PORT: num(),
  REDIS_PASSWORD: str(),
  PHRASE: str(),
  MORALIS_STREAM_ID: str(),
  TIME_LOCK: num(),
  OWNER_KEY: str(),
  ROUTER_PANCAKE: str(),
  WBNB: str(),
  CURRENCY_USDT: str(),
  SELL_CONTRACT: str(),
  PHRASE_SWAP: str(),
  PRIVATE_KEY_FEE_SWAP: str(),
  PATH_SEEDING: str(),
  MORALIS_API_KEY: str(),
});

export default env;
